### ISSUE TITLE
h1 faux bolding

### ISSUE THREAD

**Issue by micahmicah** [risd/risd-graduate-exhibition-2015#4]
The text "RISD Grad Show" is being faux bolded by h1 defaults. 
![screen shot 2015-05-06 at 10 10 35 am](https://cloud.githubusercontent.com/assets/1166088/7494848/2ee245ba-f3d8-11e4-883f-3974cacc2d14.png)

By adding `font-weight: normal;` the browser will not add extra "blubber" to the letters:

![screen shot 2015-05-06 at 10 10 50 am](https://cloud.githubusercontent.com/assets/1166088/7494863/448b0960-f3d8-11e4-8ab0-0c1573106a5f.png)

**Comment by rubillionaire** [comment]
79ba19f5de9808d493a66fe02924dae51b78f99a

Just needs to be updated on the FTP.
